---
- name: Create user on remote
  hosts: apps
  become: yes
  tasks:
  - name: Create user
    user: 
      name: testuser
      update_password: always #or we can use oncreate
      password: "{{ 'nkjs@080' | password_hash('sha512') }}" # This will ensure the password is hashed
      # as providing password as just string like 'naveen@080' will not work due to security reasons while
      # configuring user on remote server over a network